name: CI/CS section 7 

on:
  push:
    branches:
      - master
    # TO DO. limit these workflows so that they trigger only when a particular path is pushed.
    #paths:
    #  - 'reactapp/frontend/**'

jobs:
  execute-tests:
    name:  build and run test 
    # this job runs on Linux
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: build
        run: |
          cd reactapp/frontend
          docker build -t reactapp_tag -f Dockerfile.dev .
        # -- --coverage means npm run will exit command line when tests are done
      - name: run tests
        run:
          docker run -it CI=true reactapp_tag npm run test -- --coverage

