name: CI/CS section 7 

on:
  push:
    branches:
      - master
    # TO DO. limit these workflows so that they trigger only when a particular path is pushed.
    #paths:
    #  - 'reactapp/frontend/**'

jobs:
  execute-tests:
    name:  build and run test 
    # this job runs on Linux
    runs-on: ubuntu-latest
    steps:
    #- uses: ./.github/workflows/deploy
      #with:
      #  path: reactapp/frontend
      #  dockerfile: reactapp/frontend/Dockerfile.dev
      # add tag if u want, reactapp_tag in this case
      # run: docker build -f Dockerfile.dev . 
    #- uses: ./.github/workflows/deploy
      - uses: actions/checkout@v2
      #- uses: ./.github/workflows/deploy
        #working-directory: reactapp/frontend/
      - name: build
        run: |
          cd reactapp/frontend
          docker build -f Dockerfile.dev .
        #docker build . --file Dockerfile.dev --tag reactapp_tag
        # -- --coverage mean npm run will exist command line when tests are done
      - name: run tests
        run: |
          cd reactapp/frontend
          docker run -it reactapp_tag npm run test -- --coverage

